---
title: "Summertime with ggvis and shiny"
author: "Alex Shum and Ian Lyttle"
runtime: shiny
---

This summer we worked together to build an online course to teach applied statistics within Schneider Electric. Part of what motivated our approach was seeing [Chris Wild’s approach](https://www.stat.auckland.ac.nz/~wild/talks/09.USCOTS.wild.html) to teaching statistics, which was brought to our attention by Thomas Lumley, during his visit to Iowa State earlier this year. 

The thought was to build interactive web applications using ggvis and shiny. This was particularly challenging because, as you know, ggvis is still very much being developed. Shiny also underwent big changes this summer, as we can now embed shiny applications in rmarkdown documents. It was very exciting to come into work and to have new capabilities appear on github on a near-daily basis.

This talk will have a couple of parts. The first part will be to show you some of the more interesting aspects (at least we think so) among the new capabilities of ggvis and shiny. We will go over some of the things we found out the hard way, and some hacks that may be useful. The second part will be to show off some of the apps that we made this summer - some are done, some are still being finished. 

We don’t have slides - instead, we have a collection of half-baked vignettes: 

### ggvis

* [Piping](piping.Rmd)
* [Datetimes](scale_datetime.Rmd)
* [Number of Marks](number_of_marks.Rmd)
* [layer_images()](layer_images.Rmd)
* [Intermediate - Compute](intermediate_compute.Rmd)
* [Intermediate - Transform](intermediate_transform.Rmd)

### shiny

* [ggvis and Reactives](ggvis_reactives.Rmd)
* [Widgets](shiny_widgets.Rmd)
* [Building a shiny-rmarkdown site](building.Rmd)
* [Building a static-rmarkdown site](http://ijlyttle.github.io/isugg_ggvis_shiny/static_ggvis.html)
* [shinyBS!](shinyBS.Rmd)

### Some (almost) finished apps to show off (more to come)

* https://ijlyttle.shinyapps.io/intro-video/
* https://ijlyttle.shinyapps.io/random-industry/
* https://ijlyttle.shinyapps.io/random-video/

We'd like to thank RStudio, and Winston Chang in particular, for their patience in answering questions, fixing bugs (and pointing out when they are not bugs), and gracious advice.