---
title: "interactive_ggvis"
output: html_document
runtime: shiny
---

If we generate a document through shiny then we can have an interactive ggvis using shiny.

```{r, warning=FALSE, message=FALSE}
library(ggvis)
library(dplyr)

data = cocaine %>% 
  group_by(state) %>% 
  mutate(price_by_wt = price/weight) %>% 
  summarise(mean_price_by_wt = mean(price_by_wt)) %>% 
  arrange(desc(mean_price_by_wt)) %>% 
  mutate(rank = 1:45)

map_data = ggplot2::map_data("state") %>% 
  left_join(data.frame(state = state.abb, region = tolower(state.name)), by = "region") %>%
  select(long, lat, group, state) 

df = data %>% 
  left_join(map_data, by = "state") %>%
  mutate(clicked = 0)

df[df$state == "WA",]$clicked = 1
df$clicked = as.factor(df$clicked)
df = df[complete.cases(df),]
```

```{r widget, warning=FALSE, message=FALSE}

widget_example <- function() {
  shinyApp(
    ui = fluidPage(responsive = FALSE,
            fluidRow(
              column(width = 6,
                ggvisOutput("gg_map")
              ),
              
              column(width = 6,
                ggvisOutput("gg_rank")
              )
            )
    ), #ui
    
    server = function(input, output, session) {
      selected = reactiveValues(group = 56)
      
      rct_get_data = reactive({
        df$clicked = 0
        df[df$group == selected$group,]$clicked = 1
        
        df
      })
      
      rct_get_data2 = reactive({ 
        geo = rct_get_data()
        selected_state = unique(geo[geo$clicked == 1,]$state)
        
        data$selected = 0
        data[data$state == selected_state,]$selected = 1
        data$selected = as.factor(data$selected)
        
        data
      })
      
      click = function(data, ...) {
        selected$group = data$group
      }
      
      #map
      rct_get_data %>% ggvis(x = ~long, y = ~lat) %>% group_by(group) %>%
        layer_paths(fill = ~clicked) %>% 
        hide_legend("fill") %>%
        handle_click(on_click = click) %>% 
        bind_shiny("gg_map")
      
      #dotplot
      rct_get_data2 %>% ggvis(x = ~mean_price_by_wt, y = ~state) %>%
        layer_points(fill = ~selected) %>% hide_legend("fill") %>% bind_shiny("gg_rank")
      
    } #server
    
  ) #shinyAPP
}
```


```{r runWidget2}
widget_example()
```