---
title: "Number of marks"
runtime: shiny
---



```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dpcDataSE) # github: SE-EEI/dpcDataSE
library(dplyr)
library(ggvis)
library(shiny)
```

```{r echo=FALSE}
df_intensity <- dpcDataSE::conf_room_bumper$df_intensity
npx <- 128
npy <- 144

df_int <- df_intensity %>% 
  filter(row == 3 & col == 5) %>% # just one part of the image... 18000 pixels
  transmute(                      # new dplyr verb, combines mutate and select
    intensity = ifelse(intensity < 1, intensity, intensity * (1 - 1.e-8)),
    px = ((px - 1) %% npx) + 1, 
    py = ((py - 1) %% npy) + 1
  ) 

df_img <- 
  data.frame(
    x = 0, 
    x2 = 128,
    y = 144, 
    y2 = 0,
    url = "https://se-eei.github.io/dpcDataSE/inst/img/conf_room_bumper/img_grey/conf_room-000-003-005.jpg"  
  )

gg_img <-
df_img %>%
  ggvis() %>%
  layer_images(x = ~x, x2 = ~x2, y = ~y, y2 = ~y2, url := ~url) %>%
  scale_numeric("y", reverse = TRUE) %>%
  hide_axis("x") %>%
  hide_axis("y") %>%
  set_options(
    height = 288, 
    width = 256, 
    keep_aspect = TRUE, 
    renderer = "canvas"
  ) 

select_sample <- selectInput(
  "nsample",
  "Size of sample",
  choices = 2^(2*seq(0, 7))
)

slider_nbin <- sliderInput(
  "nbin",
  label = "Number of bins",
  min = 1, 
  max = 100, 
  value = 30
)

button_resample <- actionButton(
  "resample",
  label = "Resample",
  icon = icon("random")
)

slider_size_points <- sliderInput(
  "size_points",
  label = "Size of points",
  min = 1, 
  max = 100, 
  value = 50
)

rct_df_sample <- reactive({
  
  input$resample
  
  if (is.null(input$nsample)) {
    index_sample <- NULL
  } else {
    index_sample <- sample(nrow(df_int), input$nsample)
  }
 
  df_int[index_sample, ]

})

rct_binwidth <- reactive({
  
  if (is.null(input$nbin)) {
    binwidth <- 1
  } else {
    binwidth <- 1/input$nbin
  }
  
})

gg_img_sample <- 
  gg_img %>%
  layer_points(
    x = ~px + 0.5,
    y = ~py + 0.5,
    size := reactive(input$size_points),
    fill := "red", 
    fillOpacity := 0.5,
    stroke := "red", 
    data = rct_df_sample
  )
  
gg_hist <- 
  rct_df_sample %>%
  ggvis(x = ~intensity) %>%
  layer_histograms(
    binwidth = rct_binwidth,
    fill := "red", 
    fillOpacity := 0.5,
    stroke := "red"
  ) %>%
  scale_numeric("x", domain = c(0, 1)) 
```

Remeber this? We have added a "Size of points" slider. Also, we have modified the choices for the number of samples, so that you can see how things slow down as you put more points in your sample.

```{r, echo=FALSE}
select_sample
slider_size_points
slider_nbin
button_resample
```

```{r, echo=FALSE, fig.height=2, fig.width=3}
gg_img_sample
gg_hist
```





